config/routes.rb
Rails.application.routes.draw do
  resources :chuls
  devise_for :users
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chul.rb
class Chul < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/chuls_controller.rb
class ChulsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_chul, only: [:show, :edit, :update, :destroy]

  # GET /chuls
  # GET /chuls.json
  def index
    @chuls = Chul.all
  end

  # GET /chuls/1
  # GET /chuls/1.json
  def show
  end

  # GET /chuls/new
  def new
    @chul = Chul.new
  end

  # GET /chuls/1/edit
  def edit
  end

  # POST /chuls
  # POST /chuls.json
  def create
    @chul = Chul.new(chul_params)

    respond_to do |format|
      if @chul.save
        format.html { redirect_to @chul, notice: 'Chul was successfully created.' }
        format.json { render :show, status: :created, location: @chul }
      else
        format.html { render :new }
        format.json { render json: @chul.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chuls/1
  # PATCH/PUT /chuls/1.json
  def update
    respond_to do |format|
      if @chul.update(chul_params)
        format.html { redirect_to @chul, notice: 'Chul was successfully updated.' }
        format.json { render :show, status: :ok, location: @chul }
      else
        format.html { render :edit }
        format.json { render json: @chul.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chuls/1
  # DELETE /chuls/1.json
  def destroy
    @chul.destroy
    respond_to do |format|
      format.html { redirect_to chuls_url, notice: 'Chul was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chul
      @chul = Chul.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chul_params
      params.require(:chul).permit(:title, :content)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    case flash_type
      when "success"
        "alert-success"   # Green
      when "error"
        "alert-danger"    # Red
      when "alert"
        "alert-warning"   # Yellow
      when "notice"
        "alert-info"      # Blue
      else
        flash_type.to_s
    end
  end
end

app/helpers/chuls_helper.rb
module ChulsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/chuls/_form.html.erb
<%= simple_form_for(@chul) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :content %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/chuls/edit.html.erb
<h1>Editing Chul</h1>

<%= render 'form', chul: @chul %>

<%= link_to 'Show', @chul %> |
<%= link_to 'Back', chuls_path %>

app/views/chuls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Chuls</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chuls.each do |chul| %>
      <tr>
        <td><%= chul.title %></td>
        <td><%= chul.content %></td>
        <td><%= link_to 'Show', chul %></td>
        <td><%= link_to 'Edit', edit_chul_path(chul) %></td>
        <td><%= link_to 'Destroy', chul, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chul', new_chul_path %>

app/views/chuls/new.html.erb
<h1>New Chul</h1>

<%= render 'form', chul: @chul %>

<%= link_to 'Back', chuls_path %>

app/views/chuls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @chul.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @chul.content %>
</p>

<%= link_to 'Edit', edit_chul_path(@chul) %> |
<%= link_to 'Back', chuls_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectLrdserver</title>
    <%= csrf_meta_tags %>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">AuthBlog</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><%= link_to "Home", root_path %></li>
            <li><%= link_to "Posts", "#" %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.email %> <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "My Profile", edit_user_registration_path %></li>
                    <li><%= link_to "Sign out", destroy_user_session_path, method: :delete, data: { confirm: "Are you sure?" } %></li>
                  </ul>
                </li>
            <% else %>
                <li><%= link_to "Sign in", new_user_session_path %></li>
                <li><%= link_to "Sign up", new_user_registration_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <%= render partial: "shared/flash_messages", flash: flash %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
    <div class="alert <%= bootstrap_class_for(type) %> alert-dismissable fade in">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= message %>
    </div>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>
<% if user_signed_in? %>
    <p>현재 로그인된 유저의 이메일 : <%= current_user.email %></p>
    <p><%= link_to "로그아웃", destroy_user_session_path, method: :delete, data: { confirm: "Are you sure?" } %></p>
<% else %>
    <p><%= link_to "로그인", new_user_session_path %></p>
<% end %>